bc_signature/urls.py
from django.urls import path
import bc_signature.views as bc_signature_views
from django.views.generic.base import TemplateView
from django.contrib.auth.views import logout
from django.conf import settings

app_name = 'bc_signature'
urlpatterns = [
    # path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('login/', bc_signature_views.Login.as_view(), name='login'),
    path('signup/', bc_signature_views.Signup, name='signup'),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    # main url
    path('register_wallet/', bc_signature_views.RegisterWallet, name='get_wallet'),
    path('register_rsa/', bc_signature_views.ResgisterRSA, name='get_rsa_account'),
    path('sign/', bc_signature_views.sign_contract, name='sign'),
    path('my_transactions/', bc_signature_views.list_transaction_of_current_user, name = 'my_transactions'),
    path('my_transactions/b_side', bc_signature_views.list_transaction_for_b_side, name = 'my_transactions_b_side'),
    path('detail_transaction/<str:transaction_hash>', bc_signature_views.detail_transaction, name = 'detail_transaction'),
    path('check_signature/<str:transaction_hash>', bc_signature_views.check_signature, name = 'check_signature'),
    path('sign_transaction/', bc_signature_views.sign_transaction, name = 'sign_transaction'),
    path('', bc_signature_views.list_all_user, name = 'home'),
    path('transactions_of_user/<str:username>', bc_signature_views.list_transaction_by_account, name = 'transactions_of_user')
    
    
]

digital_sign/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bc_signature.urls'))
]

bc_signature/models.py
from django.db import models
from django.contrib.auth.models import User

class WalletAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='users_wallet')
    wallet_private_key = models.CharField( max_length=100,blank=True, null=True)
    wallet_account = models.CharField( max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.wallet_account


class RSAAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='users_rsa')
    rsa_private_key = models.CharField( max_length=1000, blank=True, null=True)
    rsa_public_key = models.CharField( max_length=1000, blank=True, null=True)

    def __str__(self):
        return self.user.username

bc_signature/views.py
from django.shortcuts import render,redirect
from django.template import loader
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import views as base_auth_view
import requests
from bc_signature import models, my_rsa
import json
# ---- for RSA- 
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
from Crypto.Hash import SHA

from ast import literal_eval # convert string to tuple
#-----
from eth_account import Account
import base64
import json
import random

# class Signup(generic.CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy('bc_signature:login')
#     template_name = 'signup.html'

headers = {'content-type': 'application/json'}

def Signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'sign up successful')
            return redirect('bc_signature:login')
    else:
            form = UserCreationForm()
    return render(request, 'signup.html',{'form':form})


class Login(base_auth_view.LoginView):
    template_name = 'login.html'


def RegisterWallet(request):
    data = ''
    list_user_id_in_wallets = []
    if request.user.is_authenticated:
        id_user = request.user.id
        u = models.User.objects.get(id=id_user)
        result , list_user_id_in_wallets = check_wallet_account_exist(id_user)
        if not result:
            wallet = models.WalletAccount() 

            # list_node = get_all_nodes()
            # url = list_node[random.randrange(0,len(list_node)-1)]
            # print(" url register wallet ", url)
            # rep = requests.get(f'http://{url}/account/{id_user}')
            # data = rep.text
            # data = json.loads
            for i in range(2200, 2210):
                try:
                    rep = requests.post(f'http://172.30.0.1:{i}/account/{id_user}')
                    data = rep.text
                    print(type(data))
                    print(data)
                    data = json.loads(data)
                    if data:
                        break
                    else:
                        pass
                except:
                    pass
            # save json in models:
            wallet.user = u
            wallet.wallet_private_key = data['private_key']
            wallet.wallet_account  = data['address']
            wallet.save()
        else:
            data = 'user already have an wallet account '
            info = ""
            for item in list_user_id_in_wallets:
                if id_user == item:
                    i = models.WalletAccount.objects.get(user=u)
                    info = f"account : {i.wallet_account}"
                    print(i.wallet_account)
                    print(i.wallet_private_key)
            data += info
    else:
        data = "User need to log in!"           
    return render(request, 'get_account.html', {'data':data})


def ResgisterRSA(request):
    data = ''
    list_user_id_has_rsa_key = []
    if request.user.is_authenticated:
        id_user = request.user.id
        u = models.User.objects.get(id=id_user)
        result, list_user_id_has_rsa_key = check_RSA_account_exist(id_user)
        if  not result:
            rsa_key = models.RSAAccount()
            # prikey = RSA.generate(1024)
            # pubkey = prikey.publickey()
            # save json in models:
            pub_string, pri_string = my_rsa.pri_key()
            rsa_key.user = u
            rsa_key.rsa_private_key = pri_string #prikey.exportKey().decode() # save the key in DB by String
            rsa_key.rsa_public_key  = pub_string  #pubkey.exportKey().decode()
            rsa_key.save()
            print('sau khi luu vao DB 2 ',type(pri_string)) # <class 'bytes'>
            data = f'publickey = {pub_string} and private key = {pri_string}'
        else:
            data = 'user already have an rsa keypair  '
            info = ""
            for item in list_user_id_has_rsa_key:
                if id_user == item:
                    i = models.RSAAccount.objects.get(user=u)
                    pub = i.rsa_public_key
                    pri = i.rsa_private_key
                    print(type(pub))
                    print(pub)
                    print(pri)
                    print(len(pub)) # 271
                    print(len(pri))  #882
                    info = f"publickey : {pub} and private_key: {pri}"
            data += info
    else:
        data = "User need to log in!"           
    return render(request, 'get_account.html', {'data':data})


def check_RSA_account_exist(user_id):
    list_user_id_has_rsa_key = []
    u = models.User.objects.get(id=user_id)
    rsa_keys = models.RSAAccount.objects.all()
    for key in rsa_keys:
            list_user_id_has_rsa_key.append(key.user.id)
    if u.id not in list_user_id_has_rsa_key:
        return False, list_user_id_has_rsa_key
    else:
        return True, list_user_id_has_rsa_key


def check_wallet_account_exist(user_id):
    list_user_id_has_wallet_key = []
    u = models.User.objects.get(id=user_id)
    wallet_keys = models.WalletAccount.objects.all()
    for key in wallet_keys:
            list_user_id_has_wallet_key.append(key.user.id)
    if u.id not in list_user_id_has_wallet_key:
        return False, list_user_id_has_wallet_key 
    else:
        return True, list_user_id_has_wallet_key
        

def get_all_nodes():
    list_node = []
    for i in range(2200, 2210):
        try:
            print(" i = ", i)
            # get list of nodes 
            rep = requests.get(f'http://172.30.0.1:{i}/nodes')
            list_node = json.loads(rep.text)
            print("cac node: ",list_node)
            if list_node:
                print(" okie")
                break
            else:
                pass
        except:
            pass
            
    return list_node['nodes']



def sign_contract(request):
    list_user_RSA = []
    list_user = models.User.objects.exclude(id = request.user.id)
    for i in list_user:
        do_have_RSA, _ = check_RSA_account_exist(i.id)
        do_have_wallet, _ = check_wallet_account_exist(i.id)
        if do_have_RSA and do_have_wallet:
            print("CO")
            list_user_RSA.append(i)
        else:
            print("CHUA CO")
    # try:
    if request.method == 'POST':
        content = request.POST['content']
        print("NOi DUNG",content)
        b_side = request.POST.get('B_side')
        print(" DA CHON: ",b_side)
        
        # if do_have_RSA and do_have_wallet:
        #     rsa_key = models.RSAAccount.objects.get(user = chosen_user)
        #     print("KEY: ",rsa_key.rsa_public_key)

        if request.user.is_authenticated:
            id_user = request.user.id
            print("user hien tai : ", request.user.username)
            result_rsa, list_user_id_has_rsa_key = check_RSA_account_exist(id_user)
            result_wallet , list_user_id_in_wallets = check_wallet_account_exist(id_user)

            chosen_user = models.User.objects.get(username = b_side)
            # do_have_RSA, _ = check_RSA_account_exist(chosen_user.id)
            # do_have_wallet, _ = check_wallet_account_exist(chosen_user.id)
            
            if result_rsa and result_wallet:
                # sign use private key
                i = models.RSAAccount.objects.get(user=request.user)
                j = models.RSAAccount.objects.get(user=chosen_user)

                k = models.WalletAccount.objects.get(user=chosen_user)
                wallet = models.WalletAccount.objects.get(user=request.user)
                    
                pub = i.rsa_public_key
                pri = i.rsa_private_key
                
                pub_b = j.rsa_public_key
                account_b = k.wallet_account
                #encrypt contract:
                encrypt_content = my_rsa.encrypt(content, pub_b)
                
                #sign:
                signature = my_rsa.sign(encrypt_content, pri) #int
                
                #verify:
                result = my_rsa.verify(encrypt_content, signature, pub)
                # pub_import = RSA.importKey(pub)
                # pri_import = RSA.importKey(pri)
                
                # h = SHA.new(content.encode())
                # print( " h = ", h)
                # signer = PKCS1_v1_5.new(pri_import)
                # signature = signer.sign(h)
                # # sig = prikey.sign(message.encode(),10)
                # print ( " signature: ")
                # print(signature)
                
                # luu = base64.b64encode(signature)
                # sign = luu.decode() # str >> save
                # print ("sign = ")
                # print(sign)
                # # verify:
                # verifier = PKCS1_v1_5.new(pub_import)
                # result = verifier.verify(h, signature)
                print("ket qua = ",result)
                
                
                # signature_json = json.dumps(signature).encode()
                # print("signature_json = ", signature_json)
                # print(signature_json)
                # print(type(signature_json))
                # verify:
                
                # chyen signature tu bytes thanh string
                # signature_json_ = signature_json.decode()

                # chuuyen signature tu string thanh list
                # sign = json.loads(signature_json)

                # chuyen signature tu list thanh tuple:
                # sign1 = tuple(sign)

                # result = pub_import.verify(content.encode(), sign1)
                
                # save on blokchhain: 
                if result:

bc_signature/templates/all_user.html
{% extends 'base.html' %}
{% block all_user %}

<style>
center {
    text-align: center;
}
#customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 50%;
    text-align: center;
}

#customers td, #customers th {
    border: 2px solid rgb(245, 250, 244);
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: center;
    background-color: #4CAF50;
    color: white;
}
a {
    color:hotpink
}

</style>

<table id="customers" >
        
  <tr>
    <th>User</th>
    
  </tr>
  
  {% for i in users %}
  <tr>
        
        <td>
            <a style="color:hotpink" href="{% url 'bc_signature:transactions_of_user' i.username %}"> {{ i.username }}
            </a>
        
            
        </td>

  </tr>
  {% endfor %}
  
</table>

  {% endblock %}

bc_signature/templates/detail_transaction.html
{% extends 'base.html' %}

{% block detail_transaction %}

<style>
#customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 80%;
    padding-bottom: 10px
}

#customers td, #customers th {
    border: 1px solid rgb(138, 185, 26);
    padding: 8px;
}

/* #customers tr:nth-child(even){background-color: #f2f2f2;} */
#customers tr {background-color: rgb(231, 216, 216);}
#customers tr:hover {background-color: rgb(212, 117, 117);}

#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
a {
    color:hotpink
}
h4 {
    color:hotpink
}
</style>

<table id="customers">
       <h4> detail transaction: {{info.transaction_hash}}</h4>
    <tr>
        <th>From</th>
        <td>{{ info.from}}</td>
    </tr>

    <tr>
        <th>To</th>
        <td>{{ info.to}}</td>
    </tr>

    <tr>
            <th>Amount</th>
            <td>{{ info.amount}}</td>
    </tr>

    <tr>
        <th>Time</th>
        <td>{{ info.time}}</td>
    </tr>

    <tr>
        <th>Public key</th>
        <td>{{ info.data.public_key}}</td>
    </tr>

    <tr>
        <th>Signature</th>
        <td>{{ info.data.signature}}</td>
    </tr>

    <tr>
        <th>Contract</th>
        <td>{{ info.data.text}}</td>
    </tr>

    <tr>
        <th>Check</th>
        <td><a href="{% url 'bc_signature:check_signature' info.transaction_hash %}">check signature</a>
            {{verify}}

        <td>
    </tr>
    {% if show_contract %}
    <tr>
            <th>Content of Contract</th>
            <td>
               
                {{show_contract}}
            <td>
        </tr>
    {% endif %}
    
        
        
</table>

  {% endblock %}

bc_signature/templates/get_account.html
{% extends 'base.html' %}

{% block wallet %}
<h4 style="color:indianred">{{ data }}</h4>
  
{% endblock %}

bc_signature/templates/get_transactions.html
{% extends 'base.html' %}

{% block transaction %}

<style>
    center {
        text-align: center;
    }
    #customers {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 50%;
        text-align: center;
    }
    
    #customers td, #customers th {
        border: 2px solid rgb(245, 250, 244);
        padding: 8px;
    }
    
    #customers tr:nth-child(even){background-color: #f2f2f2;}
    
    #customers tr:hover {background-color: #ddd;}
    
    #customers th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: center;
        background-color: #4CAF50;
        color: white;
    }
    a {
        color:hotpink
    }
    
    </style>
<h2>All transactions of user : @{{ user_.username }} </h2>
<h3 style="color:indianred">{{ mess }}</h3>

<table id="customers">
   {%if list_info_transaction%}     
  <tr>
    <th>Transactions</th>
    
  </tr>
  
  {% for i in list_info_transaction %}
  <tr>
        <td>
        <a href="{% url 'bc_signature:detail_transaction' i.transaction_hash %}"> {{ i.transaction_hash }}
        </a>
                
        </td>

  </tr>
  {% endfor %}
  {% endif %}
</table>
  
{% endblock %}

bc_signature/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login {% endblock %}


{% block content %}

<div style="border-block-end-color: gold; border: 1px" >
  <h2>Login </h2>
  
  <form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn egames-btn mt-30">Login</button>
	   
	</form>
	
	<a href="{% url 'bc_signature:signup' %}"> signup !!!</a>
	
</div>


{% endblock %}

bc_signature/templates/sign_rsa.html
{% extends 'base.html' %}
{% block sign %}

<form action="{% url 'bc_signature:sign' %}" method="POST"> 
    {% csrf_token %}
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li style="color:indianred" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}

    <h4 style="color:indianred">choose some one!</h4>
    <select required name='B_side'> 
      <option value="">None</option>
        {% for u in list_user %}
        <option value={{u.username}}> {{u.username}} </option>
      
        {% endfor %}
    </select>
  <h4 style="color:indianred">type your text for signing: </h4>
  <textarea name="content" rows="20" cols="90" required></textarea>
  <br>
  <input type="submit"  class="btn egames-btn mt-30" value="Sign with your private key"> 
</form>
{% endblock %}

bc_signature/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}
{% load static %}
{% block content %}

<div class="login">
  <h2>Sign up</h2>
  
<form method="post" action="{% url 'bc_signature:signup' %}">
  {% csrf_token %}
  <!-- catch error POST form -->
  {% for hidden in form.hidden_fields %}
	{{ hidden }}
	{% endfor %}
	{% for field in form %}
	    <div class="fieldWrapper">
	        {{ field.errors }}
	        {{ field.label_tag }} {{ field }}
	    </div>
	{% endfor %}
		<br/>
  <button type="submit" class="btn egames-btn mt-30"> Sign up</button>
</form>

	
	<a href="{% url 'bc_signature:login' %}"> login</a>
</div>


	
{% endblock %}